export const PERMISSIONS = {
  CREATE_BOOK: "CREATE_BOOK",
  UPDATE_BOOK: "UPDATE_BOOK",
  DELETE_BOOK: "DELETE_BOOK",

  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",

  CREATE_RESERVATION: "CREATE_RESERVATION",
  VIEW_BOOK_HISTORY: "VIEW_BOOK_HISTORY",
  VIEW_USER_HISTORY: "VIEW_USER_HISTORY",

  MANAGE_PERMISSIONS: "MANAGE_PERMISSIONS"
};
